[package]
name = "paper-benchmark"
version = "1.2.2"
edition = "2021"

[dependencies]
paper_client = { git = "ssh://git@github.com/Paper-Book/paper-client-rs.git", tag = "v2.3.3" }
kwik = { git = "https://github.com/KiaShakiba/kwik.git", tag = "v1.6.2" }
clap = { version = "4.5.4", features = ["derive"] }
byteorder = "1.5.0"
crossbeam-channel = "0.5.13"
tokio = { version = "1", features = ["full"] }

[[bin]]
name = "paper-benchmark"
path = "src/main.rs"
