[package]
name = "paper-benchmark"
version = "1.1.3"
edition = "2021"

[dependencies]
paper_client = { git = "ssh://git@github.com/Paper-Book/paper-client-rs.git", version = "2.0.5" }
kwik = { git = "https://github.com/KiaShakiba/kwik.git", tag = "v1.0.0" }
clap = { version = "4.4.7", features = ["derive"] }
byteorder = "1.5.0"
crossbeam-channel = "0.5.12"
tokio = { version = "1", features = ["full"] }

[[bin]]
name = "paper-benchmark"
path = "src/main.rs"
