[package]
name = "paper-benchmark"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
paper_client = { git = "ssh://git@github.com/Paper-Book/paper-client-rs.git", version = "0.1.0" }
kwik = { git = "https://github.com/KiaShakiba/kwik-rs.git", version = "0.1.0" }
clap = { version = "4.4.7", features = ["derive"] }
byteorder = "1.5.0"
